resources:
  - name: repository
    type: git
    source:
      branch: main
      uri: https://github.com/tkornacki/sdd.git

jobs:
  - name: build-apps
    plan:
      - get: repository
        trigger: true
      - task: build-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/build_apps.py
          outputs:
            - name: apps
            - name: repository
  - name: ci-pipeline
    plan:
    - get: repository
      trigger: false # TODO: Set this on a timer.
    - set_pipeline: ci.yaml
      file: repository/pipelines/ci.yaml
    # plan:
    #   - get: repository
    #     trigger: false # TODO: Set this on a timer.
    #   - task: deploy-apps
    #     config:
    #       platform: linux
    #       image_resource:
    #         type: docker-image
    #         source:
    #           repository: python
    #       inputs:
    #         - name: repository
    #       run:
    #         path: python
    #         args:
    #           - repository/scripts/deploy_apps.py
    #   - task: run-verification
    #     config:
    #       platform: linux
    #       image_resource:
    #         type: docker-image
    #         source:
    #           repository: python
    #       inputs:
    #         - name: repository
    #       run:
    #         path: python
    #         args:
    #           - repository/scripts/run_verification.py
    #         #TODO: Post status message after running the verification script