resources:
  - name: repository
    type: git
    source:
      branch: main
      uri: https://github.com/tkornacki/sdd.git

jobs:
  - name: build-apps
    plan:
      - get: repository
        trigger: true
      - task: build-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/build_apps.py
          outputs:
            - name: apps
            - name: repository
  - name: ci
    plan:
      - get: repository
        trigger: false # TODO: Set this on a timer.
        passed: [build-apps]
      - task: deploy-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/deploy_apps.py
              - -e ci
      - task: run-verification
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/run_verification.py
            #TODO: Post status message after running the verification script
  - name: qa-mco
    plan:
      - get: repository
        trigger: false
        passed: [build-apps, ci]
      - task: deploy-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/deploy_apps.py
      - task: run-verification
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/run_verification.py
  - name: staging
    plan:
      - get: repository
        trigger: false
        passed: [build-apps, ci]
      - task: deploy-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/deploy_apps.py
      - task: run-verification
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/run_verification.py
  - name: performance-tests
    plan:
      - get: repository
        trigger: false
        passed: [ci, staging, qa-mco]
      - task: run-performance-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/run_performance_tests.py
