resources:
  - name: repository
    type: git
    source:
      branch: main
      uri: https://github.com/tkornacki/sdd.git

jobs:
  - name: ci-pipeline
    plan:
      - get: repository
        trigger: false # TODO: Set this on a timer.
      - task: deploy-apps
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/deploy_apps.py
      - task: run-verification
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
          inputs:
            - name: repository
          run:
            path: python
            args:
              - repository/scripts/run_verification.py
            #TODO: Post status message after running the verification script